config/routes.rb
StayHereTonight::Application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  resources :listings
  devise_for :users
  resources :users, only: [:show, :edit]
  resources :bookings
  root to: 'listings#index'
 end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :listing
  belongs_to :user

  validates :start_date, :presence => true
  validates :end_date, :presence => true
  validate :free_dates

  def date_range
    (self.start_date..self.end_date).to_a
  end

  def booking_months
    months =[]
    (self.start_date..self.end_date).to_a.each do |d|
      months << d.month
    end
  months.uniq
  end

  def free_dates
    self.listing.bookings.each do |b|
      b.date_range.each do |date|
        if self.date_range.include?(date)
          errors[:base] << "Dates Taken"
        end
      end
    end
  end
end

app/models/listing.rb
class Listing < ActiveRecord::Base
  belongs_to :user
  do_not_validate_attachment_file_type :photo
  has_attached_file :photo, styles: { small: '100x100>', medium: '250x250>', large: '400x400>' }

  has_many :bookings
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_attached_file :avatar, styles: { medium: '250x250>', large: '400x400>' }
  do_not_validate_attachment_file_type :avatar
  has_many :listings
  has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?


  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :email
    devise_parameter_sanitizer.for(:sign_up) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :avatar
    devise_parameter_sanitizer.for(:account_update) << :email
  end



end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @booking = Booking.new(booking_params)

    if @booking.save
      @booking.update(user_id: current_user.id)
      flash[:notice] = "Booked! Enjoy your stay from #{@booking.start_date} to #{@booking.end_date}"
      redirect_to :back
    else
      redirect_to :back
      flash[:notice] = @booking.errors.messages

    end
  end

private
  def booking_params
    params.require(:booking).permit(:start_date, :end_date, :listing_id)
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController

  def index
    respond_to do |format|
      format.html { @listings = Listing.all }
      format.js {@listings = Listing.basic_search(params[:search])}
    end
  end

  def show

    @date = params[:month] ? Date.parse(params[:month]) : Date.today

    @listing = Listing.find(params[:id])
    @booking = Booking.new
    @bookings = @listing.bookings
  end

  def destroy
    Listing.find(params[:id]).destroy
    redirect_to root_path
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = Listing.new(listing_params)
    if @listing.save
      current_user.listings << @listing
      redirect_to user_path(current_user)
    else
      flash[:notice] = 'HAHA Learn how to fill in a form.'
      render 'new'
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to user_path(current_user)
    else
      render 'edit'
    end
  end

private
  def listing_params
    params.require(:listing).permit(:address, :description, :photo, :jacuzzi, :dominatrix_dungeon, :meat_hooks, :torture_dungeon, :pit_of_despair, :smelly_dog)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end




  def show

    @user = User.find(params[:id])
    d = Date.new(1900)
    @past_bookings = @user.bookings.where(end_date: (d..Date.today) )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/new.html.erb
  <% if @booking.errors.any? %>
    <h2>Form is invalid</h2>
      <ul>
        <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
<%= form_for @booking do |f| %>
  <%= f.label :start_date %><br>
  <%= f.date_field :start_date %><br>

  <%= f.label :end_date %><br>
  <%= f.date_field :end_date %><br>

  <%= f.submit 'Book!', :class => "btn btn-success" %>
<% end %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h2>Form is invalid</h2>
    <ul>
      <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
      <% end %>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>StayHereTonight</title>
  <%= favicon_link_tag image_path('favicon.ico') %>
  <%= stylesheet_link_tag    "application", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application",  "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js", "data-turbolinks-track" => true %>
  <title><%= yield :title %></title>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="container">
    <div class="navbar navbar-default">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="<%=root_path%>">Come back here</a>
  </div>
  <div class="navbar-collapse collapse navbar-responsive-collapse">
    <ul class="nav navbar-nav">

    </ul>
    <form class="navbar-form navbar-left" id="listingSearch" action='/listings' data-remote="true">
      <input type="text" class="form-control col-lg-8" id="search" placeholder="Search" name='search'>

    </form>
    <ul class="nav navbar-nav navbar-right">
      <% if current_user %>
        <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
        <li><%= link_to current_user.username, user_path(current_user) %></li>

      <% else %>
        <li><a href="<%= new_user_session_path %>">Sign In</a></li>
         <li><a href="<%= new_user_registration_path %>">Sign Up</a></li>
      <% end %>
    </ul>
  </div>
  </div>
  <% flash.each do |name, msg| %>
  <%= content_tag :div, msg, id: "flash_#{name}" %>
  <% end %>
    <%= yield %>
  <div class="results">
  </div>

</div>
</body>
</html>

app/views/listings/_list.html.erb
<ul class="listingList">
  <% @listings.each do |listing| %>
    <li class="listing"> <%= image_tag listing.photo.url(:small) %>
      <% if listing.user == current_user %>
        <%= listing.address %> | <%= listing.description %> | <%= link_to "Edit Listing", edit_listing_path(listing)%></li>
      <% else %>
        <%= listing.address %> | <%= listing.description %> | <%= link_to "Book Listing", listing_path(listing) %>
      <% end %>
  <% end %>
</ul>

app/views/listings/edit.html.erb
  <% if @listing.errors.any? %>
    <h2>Form is invalid</h2>
      <ul>
        <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
<%= form_for @listing do |f| %>
  <%= f.label :address %><br>
  <%= f.text_field :address %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.label :photo %>
  <%= f.file_field :photo %>

  <%= f.submit 'Update listing' %>
<% end %>
</br>

<%= link_to "Delete Listing", listing_path(@listing), method: :delete, class: 'btn btn-danger' %>

app/views/listings/index.html.erb
<%= render 'list' %>

app/views/listings/index.js.erb
$(function(){
  $('.listingList').html('').append("<%= j render 'list' %>")
});

app/views/listings/new.html.erb
  <% if @listing.errors.any? %>
    <h2>Form is invalid</h2>
      <ul>
        <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
        <% end %>
      </ul>
  <% end %>
<%= form_for @listing do |f| %>
  <%= f.label :address %><br>
  <%= f.text_field :address %><br>

  <%= f.label :city %><br>
  <%= f.text_field :city %><br>

  <%= f.label :state %><br>
  <%= f.text_field :state %><br>

  <%= f.label :zip %><br>
  <%= f.text_field :zip %><br>

  <%= f.label :description %><br>
  <%= f.text_area :description %><br>

  <%= f.label :dominatrix_dungeon %>
  <%= f.check_box :dominatrix_dungeon %><br>

  <%= f.label :meat_hooks %>
  <%= f.check_box :meat_hooks %><br>

  <%= f.label :torture_dungeon %>
  <%= f.check_box :torture_dungeon %><br>

  <%= f.label :smelly_dog %>
  <%= f.check_box :smelly_dog %><br>

  <%= f.label :pit_of_despair %>
  <%= f.check_box :pit_of_despair %><br>

  <%= f.label :jacuzzi %>
  <%= f.check_box :jacuzzi %><br>

  <%= f.label :photo %>
  <%= f.file_field :photo %><br>


  <%= f.submit 'Add listing' %><br>
<% end %>

app/views/listings/show.html.erb
 <div class="col-lg-12" id="listPic">
  <%= image_tag @listing.photo.url(:large) %>
  <h2><%= @listing.address %></h2><hr>
</div>

<div class="col-lg-12">
  <h3> Description</h3>
  <h5><%= @listing.description %></h5>
</br>
  Meat Hook?
  <% if @listing.meat_hooks %>
    YES!
  <% else %>
    NO!
   <% end %>
 </br>
     Dominatrix Dungeon?
  <% if @listing.dominatrix_dungeon %>
    YES!
  <% else %>
    NO!
   <% end %>
   <br>
     Torture Chamber?
  <% if @listing.torture_dungeon %>
    YES!
  <% else %>
    NO!
   <% end %>
   <br>
     Pit of Despair?
  <% if @listing.pit_of_despair %>
    YES!
  <% else %>
    NO!
   <% end %>
  </br>
     Smelly Dog?
  <% if @listing.smelly_dog %>
    YES!
  <% else %>
    NO!
   <% end %>
   <br>
    Jacuzzzi?
  <% if @listing.jacuzzi %>
    YES!
  <% else %>
    NO!
   <% end %>
</div>

<div class="col-lg-11" id="bookingCol">
  <%= render 'layouts/errors', :object => @booking %>

  <%= form_for @booking do |f| %>
    <%= f.label :start_date %><br>
    <%= f.date_field :start_date %><br>

    <%= f.label :end_date %><br>
    <%= f.date_field :end_date %><br>

    <%= f.hidden_field :listing_id, value: @listing.id %><br>

    <%= f.submit 'Book!', :class => "btn btn-success" %>
  <% end %>
  <br>
</div>
<div class='cal'>
  <div class="col-lg-15">
    <div id="calendar">
      <h2 id="month">
        <%= link_to "<", :month => (@date.beginning_of_month-1).strftime("%Y-%m-01") %>
        <%= h @date.strftime("%B %Y") %>
        <%= link_to ">", :month => (@date.end_of_month+1).strftime("%Y-%m-01") %>
      </h2>
      <%= calendar_for @bookings, :month => @date.month do |c| %>

        <%= c.head("Monday","Tuseday","Wednesday","Thursday","Friday","Saturday","Sunday") %>
        <%= c.day(:day_method => :start_date) do |d, booking| %>
          <%= d.day %>
            <ul>
              <% for booking in @bookings %>
                <% if booking.date_range.include?(d) && booking.booking_months.include?(d.month) %>
                  <li class="red"> Reserved </li>
                <% end %>
              <% end %>
            </ul>
        <% end %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<h1> Come and stay here...</h1>

app/views/users/listings.html.erb
<h1>Users#listings</h1>
<p>Find me in app/views/users/listings.html.erb</p>

app/views/users/show.html.erb
<%= image_tag @user.avatar.url :medium %>
<h3>Your existin listins</h3>
<ul>
  <% @user.listings.each do |listing| %>
    <li class="listing"> <%= image_tag listing.photo.url(:small) %>
      <%= listing.address %> | <%= listing.description %> | <%= link_to "Edit Listing", edit_listing_path(listing)%></li>
  <% end %>
</ul>
<%= link_to "Post new Listing", new_listing_path, class: 'btn btn-alert' %>
<br>
<%= link_to "Edit Profile", edit_user_registration_path(current_user), class: 'btn btn-primary btn-sm'%>
<h3> Past Stays </h3>
<ul>

  <% @past_bookings.each do |booking| %>
   <li> <strong>From: </strong><%= booking.start_date %> <strong>to: </strong><%= booking.end_date %> <strong>at </strong><%= booking.listing.address %> </li>
   <% if booking.rating %>
    <% booking.rating.times do |s| %>
     <%= image_tag "star-on.png" %>

    <% end %>
   <% else %>
    <% (1..5).to_a.each do |s| %>
      <%= image_tag "star-off.png", class: "rating", id: s %>
    <% end %>

   <% end %>
  <% end %>
</ul>